
<!-- Start PureCSSMenu.com MENU -->
<ul class="pureCssMenu pureCssMenum0">
	<li class="pureCssMenui0"><a class="pureCssMenui0" href="<?php echo $this->baseUrl;?>/">In&iacute;cio</a></li>
	<li class="pureCssMenui0"><a class="pureCssMenui0" href="#"><span>Cadastros</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
	<ul class="pureCssMenum">
		<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Cadastros/cadempresa">Empresa</a></li>
		<li class="pureCssMenui"><a class="pureCssMenui" href="<?php echo $this->baseUrl;?>/Cadastros/caduser">Usu&aacute;rios</a></li>
	</ul>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
	<li class="pureCssMenui0"><a class="pureCssMenui0" href="#"><span>Produtos</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
	<ul class="pureCssMenum">
		<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Produtos/cadgrupo">Cadastro Grupo</a></li>
		<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Produtos/cadsgrupo">Cadastro Sub Grupo</a></li>
		<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Produtos/cadunidade">Cadastro Unidades</a></li>
	</ul>
</ul>

<!-- End PureCSSMenu.com MENU -->

<!-- (c) 2009, PureCSSMenu.com -->



<br>
