<?php
	$this->title = "Usu‡rios"; 
	$this->headTitle($this->title); 
?> 
<p>
	<a href="<?php echo $this->url(array('controller'=>'users','action'=>'add'));?>">Novo usu&aacute;rio</a>
</p>

<table> 
	<tr>
		<th>Nome</th> 
		<th>e-Mail</th> 
		<th>&nbsp;</th>
	</tr> 
	<?php
	if (count($this->user) > 0) { 
		foreach($this->users as $user) : ?> 
			<tr>
				<td><?php echo $this->escape($user->name);?></td> 
				<td><?php echo $this->escape($user->email);?></td>
				<td>
					<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
					<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$album->id));?>">Delete</a>
				</td> 
			</tr>
		<?php endforeach;
	} else {
	?>
		<tr>
			<td colspan="3">Nenhum us&aacute;rio cadastrado.</td>
		</tr>
	<?php 
	}; ?>
	 
</table>