<?php
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); 
	$this->headTitle()->setSeparator(' - '); 
	$this->headTitle('Sistema de academia');
	echo $this->doctype(); 
?> 

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?> 
		
		<!--  CSS -->
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/screen.css'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/menunovo.css'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/fieldstyle.css'); ?>
    
	    <?php echo $this->javascriptHelper(); ?>
	    <?php echo $this->headScript(); ?>		
	</head>
	<body> 
		<!-- Start: page-top-outer -->
		<div id="page-top-outer">    

			<!-- Start: page-top -->
			<div id="page-top">
	
				<!--  start top-search -->
				<div id="top-search">yeah
					<img src="<?php echo $this->baseUrl().'/imgsite/botoes/log.png';?>"/> 
					<!--  <td class="top-search-inp">-->
					<?php echo $this->usuario->nome;?>
					<a href="<?php echo $this->url(array('controller'=>'auth','action'=>'logout'));?>" id="logout"><img src="<?php echo $this->baseUrl().'/imgsite/botoes/logout.png';?>"  /></a>
				</div>
			 	<!--  end top-search -->
			 	<div class="clear"></div>

			</div>
			<!-- End: page-top -->
		</div>
		<!-- End: page-top-outer -->	
		<div class="clear">&nbsp;</div>

			<!--  start nav-outer-repeat................................................................................................. START -->
 
			<!-- start content-outer -->
			<div id="content-outer">
				<!-- start content -->
				<div id="content">
					<?php
					if (!empty($this->usuario)) 
					{
					?>
						<ul class="pureCssMenu pureCssMenum0">
							<li class="pureCssMenui0"><a class="pureCssMenui0" href="<?php echo $this->baseUrl();?>/">In&iacute;cio</a></li>
							<li class="pureCssMenui0"><a class="pureCssMenui0" href="#"><span>Cadastros</span><![if gt IE 6]></a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
							<ul class="pureCssMenum">
								<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Cadastros/cadempresa">Empresa</a></li>
								<li class="pureCssMenui"><a class="pureCssMenui" href="<?php echo $this->baseUrl;?>/Cadastros/caduser">Usu&aacute;rios</a></li>
							</ul>
							<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
							<li class="pureCssMenui0"><a class="pureCssMenui0" href="#"><span>Produtos</span><![if gt IE 6]></a><![endif]></li><!--[if lte IE 6]><table><tr><td><![endif]-->
							<ul class="pureCssMenum">
								<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Produtos/cadgrupo">Cadastro Grupo</a></li>
								<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Produtos/cadsgrupo">Cadastro Sub Grupo</a></li>
								<li class="pureCssMenui"><a class="pureCssMenui" href="/gev/Produtos/cadunidade">Cadastro Unidades</a></li>
							</ul>
						</ul>
						<br />
					<?php
					}
					?>
					<center><h1><?php echo $this->escape($this->title); ?></h1></center>
					<?php echo $this->layout()->content; ?>
				</div>
			</div> 
		</div>
	</body> 
</html>