<div id="login-holder">
	<!-- start logo -->
	<div class="logo-login">&nbsp;
	</div>	
	<input type="hidden" name="message" id="message" value="<?php echo $this->message;?>" /> 
</div> 

	<!--  start footer-left -->
	<div id="footer-left">
	
	Eliphio Barros. All rights reserved.</div>
	<!--  end footer-left -->
	<div class="clear">&nbsp;</div>

</form>
</body>

</html>

<script type="text/javascript">
//<!--
	if ($('message').value != '') {
		alert($('message').value);
	}
//-->
</script>