<? /*
/ O selectboxvetor, serve para listar descricao opcoes para usuarios, mas armazenar no banco apenas uma posicao
/ utilizacao eh criar uma matriz com duas posicoes. Primeira posicao eh a descricao, segundo eh o valor que sera armazenado.
*/ ?>

<? global $ids,$v; ?>
<label for="<? echo $ids; ?>" <? if(isset($this->labelclass[$ids])) { echo "class=\"".$this->labelclass[$ids]."\""; } ?>><? echo $v; ?></label>
<select name="<? echo $ids; ?>" id="<? echo $ids; ?>" class="texto">
<?php
eval("\$select = \$this->$ids;");
echo "<option value=\"\">Selecione</option>";
foreach ($select as $valor=>$opcao)
{
	echo "<option value=\"".$valor."\">".trim($opcao)."</option>" . chr(13) . chr(10);
}
?>
</select>
